# Generated by Django 5.1.1 on 2024-11-06 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateField(default=datetime.datetime(2024, 11, 6, 15, 33, 14, 891742, tzinfo=datetime.timezone.utc)),
        ),
    ]
