# Generated by Django 5.1.1 on 2024-10-24 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_leaveapplication_applied_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateField(default=datetime.datetime(2024, 10, 24, 17, 3, 5, 261822, tzinfo=datetime.timezone.utc)),
        ),
    ]
