# Generated by Django 5.1.1 on 2024-11-08 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_leaveapplication_applied_on_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 20, 7, 34, 461182, tzinfo=datetime.timezone.utc)),
        ),
    ]
