# Generated by Django 5.1.1 on 2024-10-24 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_leaveapplication_applied_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
