# Generated by Django 5.0.7 on 2024-08-06 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_leaveapplication_applicant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateField(default=datetime.datetime(2024, 8, 6, 7, 34, 59, 516293, tzinfo=datetime.timezone.utc)),
        ),
    ]
