# Generated by Django 5.0.7 on 2024-08-07 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_leaveapplication_applied_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateField(default=datetime.datetime(2024, 8, 7, 8, 54, 39, 440034, tzinfo=datetime.timezone.utc)),
        ),
    ]
