# Generated by Django 5.1.1 on 2024-11-12 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_name_subject_subject_name_remove_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher', to='myapp.class'),
        ),
    ]
