# Generated by Django 5.1.1 on 2024-11-13 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_teacher_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
